### PR TITLE
Fixing exception to be compatible with modern Python syntax

### PR DESCRIPTION
**Pull request by tvieira**
Hi, I've got to run taskrunner on Python 3.5 and the current syntax for these two lines is not compatible with the 3.5 version.

### CODE REVIEW

**Comment by karinqe1** [comment]
Hi, thanks for the patch. The "as" syntax is not compatible with Python 2.5 or older. Are you sure taskrunner is no longer being used on older systems? I no longer have access to the infra. If it's still being used (not likely, as 2.5 is ancient), you could change it to this: https://stackoverflow.com/questions/1373255/making-python-2-6-exception-backward-compatible/2513890#2513890

If you think that Python 2.5 is no longer used anywhere, I can merge this.

**Comment by mkollaro** [comment]
Hi, thanks for the patch. The "as" syntax is not compatible with Python 2.5 or older. Are you sure taskrunner is no longer being used on older systems? I no longer have access to the infra. If it's still being used (not likely, as 2.5 is ancient), you could change it to this: https://stackoverflow.com/questions/1373255/making-python-2-6-exception-backward-compatible/2513890#2513890

If you think that Python 2.5 is no longer used anywhere, I can merge this.

**Comment by tvieira** [comment]
Hi @mkollaro, I did a quick research within the tech list at RH and no one has confirmed they were using taskrunner with python <= 2.5. I did a research on the sys.exc_info() and I couldn't find if this is the best way to catch exception or what could go wrong. I personally think it is too much hassle to go that far backwards. Many common libraries already dropped the support to anything below 2.6. I certainly can't confirm 2.5 is no longer used anywhere (at RH).

I would be OK to merge this patch in. I will ask on python-list about catching exception through sys.exc_info as I want to here from more people, for me it is the first time I saw this way. I will wait a couple of days for someone to say something, and I ping you back here.

Thanks for the very quick response on the PR.

**Comment by mkollaro** [comment]
Hi, thanks for the commits. Could you please squash those commits together and change the version number to 0.3.0 instead of 0.3.1? Please also add a note into the commit message that support for Python 2.5 is being dropped with this commit.

**Comment by tvieira** [comment]
Thank you @mkollaro ! Sorry about the version, that was intended to be only in my fork, but I mistakenly put that on the same branch I made a PR and that came through.

**Pull request merged**
